export const GET_FOOD = 'GET_FOOD';
export const ADD_FOOD = 'ADD_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_ERROR = 'SET_CURRENT_ERROR';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_FOOD = 'UPDATE_FOOD';
export const FILTER_FOOD = 'FILTER_FOOD';
export const CLEAR_FOOD = 'CLEAR_FOOD';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const FOOD_ERROR = 'FOOD_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADD_USER_DETAILS = 'ADD_USER_DETAILS';
export const ADD_USER_DETAILS_ERROR = 'ADD_USER_DETAILS_ERROR';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';
